"""
Live fault_distance_km -- real data, no network call needed at query time.

The synthetic `fault_distance_km` was computed against 5 fake straight-line
"fault traces" (data/soil_geology/sikkim_faults.geojson, generated by
generate_synthetic_data.py -- see the "synthetic" fault_type tag on every
feature). This module replaces that with the real GEM Foundation Global
Active Faults Database (GAF-DB, CC-BY-SA 4.0,
https://github.com/GEMScienceTools/gem-global-active-faults), clipped to
a buffered NER/Himalaya bounding box (lon 84-96, lat 25-30) so faults just
outside Sikkim still count towards the nearest-fault distance --
data/soil_geology/sikkim_faults_real.geojson (73 real fault traces,
~1,680 vertices total, vs. 5 fake ones before).

Distance is true point-to-polyline (perpendicular projection onto each
segment, not just nearest vertex), computed in an equirectangular
approximation local to the query latitude -- accurate to well under 1%
at this scale, and doesn't need a full geodesic library.

Loaded once at import time and cached in memory (the clipped file is
only ~60KB), same lazy-cache contract as live_landslide_history.py.
"""
import json
import math
import os

import numpy as np

_FAULTS_PATH = os.path.join(
    os.path.dirname(__file__), "..", "data", "soil_geology", "sikkim_faults_real.geojson"
)

_fault_segments = None  # lazy-loaded, cached: list of (lat1, lon1, lat2, lon2)


def _load_faults() -> list:
    global _fault_segments
    if _fault_segments is not None:
        return _fault_segments

    segments = []
    try:
        with open(_FAULTS_PATH) as f:
            gj = json.load(f)
        for feat in gj["features"]:
            geom = feat["geometry"]
            if geom["type"] != "LineString":
                continue
            coords = geom["coordinates"]  # [(lon, lat), ...]
            for (lon0, lat0), (lon1, lat1) in zip(coords[:-1], coords[1:]):
                segments.append((lat0, lon0, lat1, lon1))
    except Exception:
        segments = []

    _fault_segments = segments
    return _fault_segments


def _point_to_segment_km(lat, lon, lat1, lon1, lat2, lon2) -> float:
    """Perpendicular point-to-segment distance in an equirectangular
    projection local to `lat` (cos-latitude scaling for longitude) --
    good to well under 1% error over distances of a few hundred km."""
    r = 6371.0
    coslat = math.cos(math.radians(lat))

    # Project to a local flat (km) frame centered on the query point.
    def to_xy(plat, plon):
        x = math.radians(plon - lon) * coslat * r
        y = math.radians(plat - lat) * r
        return x, y

    x0, y0 = 0.0, 0.0  # the query point itself, by construction
    x1, y1 = to_xy(lat1, lon1)
    x2, y2 = to_xy(lat2, lon2)

    dx, dy = x2 - x1, y2 - y1
    seg_len2 = dx * dx + dy * dy
    if seg_len2 == 0:
        t = 0.0
    else:
        t = ((x0 - x1) * dx + (y0 - y1) * dy) / seg_len2
        t = max(0.0, min(1.0, t))

    px, py = x1 + t * dx, y1 + t * dy
    return math.hypot(x0 - px, y0 - py)


def fetch_live_fault_distance(lat: float, lon: float) -> dict | None:
    """Real fault_distance_km for this exact point, against the GEM
    GAF-DB. Returns None only if the clipped fault file couldn't be
    loaded at all, so callers fall back to the synthetic value (same
    contract as the other live_* modules)."""
    segments = _load_faults()
    if not segments:
        return None

    best = min(
        _point_to_segment_km(lat, lon, lat1, lon1, lat2, lon2)
        for lat1, lon1, lat2, lon2 in segments
    )

    return {"fault_distance_km": round(best, 3)}
